export const config = {
  codigo: 'CO',
  nombre: 'Colombia',
  moneda: 'COP',
  gradoEditable: true,
  camposSumables: ['sueldoMensual', 'medicinaPrepagadaAnio'],
  campoNomina: 'sueldoMensual',
  camposEditables: [
    { campo: 'sueldoMensual', label: 'Sueldo Mensual' },
  ],
  camposReadonly: [
    {
      campo: 'bonoTarget',
      label: 'Bono CP Target',
      source: 'r',
      periodoReactivo: 'anual',
      labelFn: (r, esMensual) => `Bono CP Target (${esMensual ? 'Mensual' : 'Anual'}) (${r.nSueldos}x)`,
    },
    {
      campo: 'ingreso',
      label: 'Ingreso',
      source: 'r',
      periodoReactivo: 'toggle',
      labelFn: (r, esMensual) => `Ingreso (${esMensual ? 'Mensual' : 'Anual'})`,
    },
  ],
  opcionesTipoSalario: null,
  periodosIndividual: [1, 12],
  periodosAgregado:   [1, 12],
  defaultsAgregado:   {},
  textos: {
    tituloDesglose:         'Desglose Prestacional Mensual',
    tituloDesgloseAnual:    'Desglose Prestacional Anual',
    tituloTotalDesglose:    'Total Carga Prestacional Mensual',
    tituloTotalDesgloseAnual: 'Total Carga Prestacional Anual',
    subtituloTotalDesglose: 'Factor consolidado aplicado según matriz prestacional legal',
    tituloComposicion:      'Composición Mensual',
    kpiCarga:               'Carga Prestacional/Mes',
    kpiPct:                 '% Carga vs. Salario',
  },
};